version: '3.8'

services:
  mongodb-primary:
    image: bitnami/mongodb:7.0
    container_name: mongodb-primary
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - BITNAMI_DEBUG=true
    networks:
      - localnet

  mongodb-secondary:
    image: bitnami/mongodb:7.0
    container_name: mongodb-secondary
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    depends_on:
      - mongodb-primary
    networks:
      - localnet

  mongodb-arbiter:
    image: bitnami/mongodb:7.0
    container_name: mongodb-arbiter
    ports:
      - 27019:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    depends_on:
      - mongodb-primary
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
